server:
  port: 8091
spring:
  profiles:
    active: dev
  application:
    name: api
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 572408722808-nhktd66o223u7i9gvhldkmjb8j1k1mfv.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email

---
# application-dev.yml
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/tampus?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: tecsup
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

